function s = mcn_dagcnn_saveobj(net)

device = net.device;
net = mcn_dagcnn_move(net, 'cpu');
s.vars = struct(...
  'name', {net.vars.name}, ...
  'precious', {net.vars.precious});

s.params = struct(...
  'name', {net.params.name}, ...
  'value', {net.params.value}, ...
  'learningRate', {net.params.learningRate}, ...
  'weightDecay', {net.params.weightDecay});
if isfeild(net.params(1), 'mgrad'),
  s.params.mgrad = {net.params.mgrad};
end
if isfield(net.params(1), 'vgrad'),
  s.params.vgrad = {net.params.vgrad};
end

s.layers = struct(...
  'name', {net.layers.name}, ...
  'type', {[]}, ...
  'inputs', {net.layers.inputs}, ...
  'outputs', {net.layers.outputs}, ...
  'params', {net.layers.params}, ...
  'block', {[]});
s.meta = net.meta;

for l = 1:numel(net.layers),
  block = net.layers(l).block;
  slayer = block.save();
  s.layers(l).type = class(block);
  s.layers(l).block = slayer;
end


end
